#!/usr/bin/sh
# Auto-start applications for River WM (optimized for performance)
dunst &
waybar &
swww-daemon &
numlockx on
sh /home/huai/.config/swww_auto.sh &
sh /home/huai/.config/shutdown.sh &
# zen-browser &
# Telegram &
