#!/usr/bin/sh
# Auto-start applications for River WM (optimized for performance)
dunst &
waybar &
swww-daemon &
sh /home/huai/.config/swww_auto.sh &
sh /home/huai/.config/shutdown.sh &
sh /home/huai/.config/dwl/dwl_status.sh &
zen-browser &
Telegram &
fcitx5 -d
